name: minify

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: Use cached node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: nodeModules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          nodeModules-

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      env:
        CI: true

    - name: Minify
      run: yarn build

    - name: Commit
      run: |
        git config --global user.email Artitalk@email.com
        git config --global user.name ArtitalkJS
        git add dist/css/artitalk.min.css -f
        git add dist/js/artitalk.js -f
        git add dist/js/artitalk.min.js -f
        git commit -m ":zap: Successful minify" -a

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
